CREATE TABLE IF NOT EXISTS clean_store_transaction(
    STORE_ID VARCHAR(50),
    STORE_LOCATION VARCHAR(50),
    PRODUCT_CATEGORY VARCHAR(50),
    PRODUCT_ID INT,
    MRP FLOAT,
    CP FLOAT,
    DISCOUNT FLOAT,
    SP FLOAT,
    DATE DATE
);